
version: "3"
services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: glade_test
      POSTGRES_USER: glade
      POSTGRES_PASSWORD: glade
    ports:
      - "5433:5432"
  redis:
    image: redis:7
  backend:
    build: ../../..
    command: pytest --ds=glade.settings_test
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://glade:glade@db:5432/glade_test
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ../../..:/app
